/**
 * HVAC shell product catalog.
 * Used only as frontend shell until Control Nautas SKUs replace them.
 */

export type HvacProduct = {
  handle: string
  title: string
  brand: string
  itemNumber: string
  mfrModel: string
  price: number
  categorySlug: string
  categoryPath: string[]
  description: string
  image: string
  inStock: boolean
  rating: number
  reviewCount: number
  specs: Record<string, string>
}

const img = (key: string) => `/images/subcategories/${key}.png`

export const HVAC_PRODUCTS: HvacProduct[] = [
  // —— Heaters / Portable Jobsite ——
  {
    handle: "dayton-portable-electric-jobsite-heater-5kw",
    title: "Portable Electric Jobsite Heater, 5.0 kW, 240V, Fan-Forced",
    brand: "DAYTON",
    itemNumber: "3YU61",
    mfrModel: "3YU61",
    price: 289.99,
    categorySlug: "portable-standard-electric-jobsite-heaters",
    categoryPath: [
      "hvac",
      "heaters",
      "electric-heaters",
      "portable-electric-heaters",
      "portable-electric-jobsite-heaters",
      "portable-standard-electric-jobsite-heaters",
    ],
    description:
      "Portable standard electric jobsite heater for temporary, targeted heating. Fan-forced design with integrated stand for construction and garage use.",
    image: img("lighting_electrical"),
    inStock: true,
    rating: 4.6,
    reviewCount: 128,
    specs: {
      Voltage: "240V AC",
      Phase: "1",
      "Heating Method": "Fan Forced",
      "Power Output": "5.0 kW",
      "Air Flow": "300 CFM",
      "Country of Origin": "China",
      Certifications: "UL Listed",
      Warranty: "1 Year",
    },
  },
  {
    handle: "dayton-portable-electric-jobsite-heater-10kw",
    title: "Portable Electric Jobsite Heater, 10 kW, 240V, Fan-Forced",
    brand: "DAYTON",
    itemNumber: "3YU64",
    mfrModel: "3YU64",
    price: 449.0,
    categorySlug: "portable-standard-electric-jobsite-heaters",
    categoryPath: [
      "hvac",
      "heaters",
      "electric-heaters",
      "portable-electric-heaters",
      "portable-electric-jobsite-heaters",
      "portable-standard-electric-jobsite-heaters",
    ],
    description:
      "High-output portable electric jobsite heater for larger work areas. Operates without combustion for enclosed spaces.",
    image: img("lighting_electrical"),
    inStock: true,
    rating: 4.7,
    reviewCount: 86,
    specs: {
      Voltage: "240V AC",
      Phase: "1",
      "Heating Method": "Fan Forced",
      "Power Output": "10 kW",
      "Country of Origin": "China",
      Certifications: "UL Listed",
    },
  },
  {
    handle: "tpi-salamander-electric-heater-15kw",
    title: "Portable Salamander Electric Heater, 15 kW, 480V 3-Phase",
    brand: "TPI",
    itemNumber: "4LZ88",
    mfrModel: "FES15243A",
    price: 1299.0,
    categorySlug: "portable-salamander-electric-jobsite-heaters",
    categoryPath: [
      "hvac",
      "heaters",
      "electric-heaters",
      "portable-electric-heaters",
      "portable-electric-jobsite-heaters",
      "portable-salamander-electric-jobsite-heaters",
    ],
    description:
      "Salamander-style fan-forced electric heater delivering high-volume heat for jobsite applications without combustion exhaust.",
    image: img("brushes"),
    inStock: true,
    rating: 4.5,
    reviewCount: 42,
    specs: {
      Voltage: "480V AC",
      Phase: "3",
      "Power Output": "15 kW",
      "Heating Method": "Fan Forced",
      Certifications: "cULus",
    },
  },
  {
    handle: "qmark-infrared-portable-heater-1500w",
    title: "Portable Infrared Radiant Electric Heater, 1500W, 120V",
    brand: "QMARK",
    itemNumber: "5WAX7",
    mfrModel: "MUH152",
    price: 189.45,
    categorySlug: "portable-infrared-radiant-electric-jobsite-heaters",
    categoryPath: [
      "hvac",
      "heaters",
      "electric-heaters",
      "portable-electric-heaters",
      "portable-electric-jobsite-heaters",
      "portable-infrared-radiant-electric-jobsite-heaters",
    ],
    description:
      "Infrared radiant heater warms people and objects directly—effective in open or draft-prone jobsite areas.",
    image: img("deburring"),
    inStock: true,
    rating: 4.4,
    reviewCount: 67,
    specs: {
      Voltage: "120V AC",
      Wattage: "1500 W",
      "Heating Method": "Infrared Radiant",
      "Country of Origin": "USA",
    },
  },
  {
    handle: "chromalox-hazardous-location-heater-5kw",
    title: "Hazardous-Location Portable Electric Heater, 5 kW, Class I Div 2",
    brand: "CHROMALOX",
    itemNumber: "6HXL2",
    mfrModel: "CXH-A-05",
    price: 2185.0,
    categorySlug: "hazardous-location-portable-electric-jobsite-heaters",
    categoryPath: [
      "hvac",
      "heaters",
      "electric-heaters",
      "portable-electric-heaters",
      "portable-electric-jobsite-heaters",
      "hazardous-location-portable-electric-jobsite-heaters",
    ],
    description:
      "Explosion-resistant portable electric heater for classified hazardous locations. No combustion exhaust.",
    image: img("cutoff"),
    inStock: false,
    rating: 4.8,
    reviewCount: 19,
    specs: {
      Voltage: "480V AC",
      "Hazard Rating": "Class I, Division 2",
      "Power Output": "5 kW",
      Certifications: "UL Hazardous Location",
    },
  },

  // —— Electric Heating Cables (heat trace) ——
  {
    handle: "raychem-self-regulating-heat-trace-120v",
    title: "Self-Regulating Heating Cable, 120V, 5 W/ft, Pipe Freeze Protection",
    brand: "RAYCHEM",
    itemNumber: "2LHY4",
    mfrModel: "5BTV1-CT",
    price: 8.75,
    categorySlug: "electric-heating-cables",
    categoryPath: [
      "hvac",
      "heaters",
      "electric-heaters",
      "electric-heating-cables",
    ],
    description:
      "Self-regulating heat-trace cable for pipe freeze protection. Sold per foot; cut to length in the field.",
    image: img("buffing"),
    inStock: true,
    rating: 4.7,
    reviewCount: 203,
    specs: {
      Voltage: "120V AC",
      "Power Output": "5 W/ft",
      "Cable Type": "Self-Regulating",
      Application: "Pipe Freeze Protection",
      "Min Bend Radius": "1 in",
      "Unit of Measure": "Foot",
    },
  },
  {
    handle: "raychem-self-regulating-heat-trace-240v",
    title: "Self-Regulating Heating Cable, 240V, 10 W/ft, Roof & Gutter",
    brand: "RAYCHEM",
    itemNumber: "2LHY8",
    mfrModel: "10BTV2-CT",
    price: 11.2,
    categorySlug: "electric-heating-cables",
    categoryPath: [
      "hvac",
      "heaters",
      "electric-heaters",
      "electric-heating-cables",
    ],
    description:
      "Higher-output self-regulating cable for roof and gutter de-icing applications.",
    image: img("buffing"),
    inStock: true,
    rating: 4.6,
    reviewCount: 141,
    specs: {
      Voltage: "240V AC",
      "Power Output": "10 W/ft",
      Application: "Roof & Gutter",
      "Unit of Measure": "Foot",
    },
  },
  {
    handle: "easyheat-preassembled-heat-cable-kit-50ft",
    title: "Preassembled Heat Cable Kit, 50 ft, 120V, with Plug",
    brand: "EASYHEAT",
    itemNumber: "1NNA8",
    mfrModel: "AHB150",
    price: 124.99,
    categorySlug: "electric-heating-cables",
    categoryPath: [
      "hvac",
      "heaters",
      "electric-heaters",
      "electric-heating-cables",
    ],
    description:
      "Ready-to-install pipe freeze protection kit with grounded plug and thermostat.",
    image: img("sharpening"),
    inStock: true,
    rating: 4.3,
    reviewCount: 95,
    specs: {
      Voltage: "120V AC",
      Length: "50 ft",
      "Includes Thermostat": "Yes",
      Plug: "NEMA 5-15P",
    },
  },

  // —— Wall / Baseboard heaters ——
  {
    handle: "qmark-wall-heater-2000w-240v",
    title: "Electric Wall Heater, 2000W, 240V, Fan-Forced, White",
    brand: "QMARK",
    itemNumber: "4E227",
    mfrModel: "AWH2047",
    price: 178.5,
    categorySlug: "electric-wall-ceiling-heaters",
    categoryPath: [
      "hvac",
      "heaters",
      "electric-heaters",
      "electric-wall-ceiling-heaters",
    ],
    description:
      "Recessed or surface-mount wall heater for commercial and residential spaces.",
    image: img("vibratory"),
    inStock: true,
    rating: 4.5,
    reviewCount: 74,
    specs: {
      Voltage: "240V AC",
      Wattage: "2000 W",
      "Heating Method": "Fan Forced",
      Finish: "White",
    },
  },
  {
    handle: "markel-baseboard-heater-1000w",
    title: "Electric Baseboard Heater, 1000W, 240V, 4 ft",
    brand: "MARKEL",
    itemNumber: "3VE29",
    mfrModel: "2504T",
    price: 89.99,
    categorySlug: "electric-baseboard-heaters",
    categoryPath: [
      "hvac",
      "heaters",
      "electric-heaters",
      "electric-baseboard-heaters",
    ],
    description:
      "Convection baseboard heater for supplemental room heating. Requires line-voltage thermostat.",
    image: img("sanding"),
    inStock: true,
    rating: 4.2,
    reviewCount: 210,
    specs: {
      Voltage: "240V AC",
      Wattage: "1000 W",
      Length: "4 ft",
      "Heating Method": "Convection",
    },
  },

  // —— HVAC Controls & Thermostats ——
  {
    handle: "peco-programmable-thermostat-2h2c",
    title: "Programmable Thermostat, 2H/2C, 24 VAC",
    brand: "PECO",
    itemNumber: "59GW22",
    mfrModel: "T4522-001",
    price: 142.35,
    categorySlug: "programmable-thermostats",
    categoryPath: [
      "hvac",
      "hvac-controls-and-thermostats",
      "thermostats",
      "programmable-thermostats",
    ],
    description:
      "Programmable low-voltage thermostat for 2-heat / 2-cool systems. 24 VAC control.",
    image: img("tools_instruments"),
    inStock: true,
    rating: 4.4,
    reviewCount: 58,
    specs: {
      Voltage: "24 VAC",
      Stages: "2H/2C",
      Type: "Programmable",
      "Country of Origin": "China",
      Brand: "PECO",
    },
  },
  {
    handle: "honeywell-line-voltage-thermostat-spst",
    title: "Line-Voltage Thermostat, SPST, Non-Programmable, 120/240V",
    brand: "HONEYWELL",
    itemNumber: "2E754",
    mfrModel: "T498A1757",
    price: 46.8,
    categorySlug: "line-voltage-thermostats",
    categoryPath: [
      "hvac",
      "hvac-controls-and-thermostats",
      "thermostats",
      "line-voltage-thermostats",
    ],
    description:
      "SPST line-voltage thermostat for electric baseboard and fan-forced heaters.",
    image: img("tools_instruments"),
    inStock: true,
    rating: 4.6,
    reviewCount: 312,
    specs: {
      "Switch Type": "SPST",
      Voltage: "120/240V AC",
      Amperage: "22 A",
      Type: "Non-Programmable",
    },
  },
  {
    handle: "liebert-low-voltage-thermostat",
    title: "Low Voltage Thermostat for Precision Cooling",
    brand: "LIEBERT",
    itemNumber: "877HY8",
    mfrModel: "153210G4S",
    price: 2685.18,
    categorySlug: "low-voltage-thermostats",
    categoryPath: [
      "hvac",
      "hvac-controls-and-thermostats",
      "thermostats",
      "low-voltage-thermostats",
    ],
    description:
      "Low-voltage thermostat designed for precision cooling and critical environment systems.",
    image: img("tools_instruments"),
    inStock: true,
    rating: 4.9,
    reviewCount: 7,
    specs: {
      Brand: "LIEBERT",
      "Country of Origin": "USA",
      "Shipping Weight": "0.74 lbs",
    },
  },
  {
    handle: "johnson-controls-fan-limit-control",
    title: "Fan & Limit Control, 11 in Insertion, Adjustable",
    brand: "JOHNSON CONTROLS",
    itemNumber: "2E369",
    mfrModel: "L4064B2210",
    price: 68.25,
    categorySlug: "fan-limit-controls",
    categoryPath: [
      "hvac",
      "hvac-controls-and-thermostats",
      "hvac-equipment-controls",
      "fan-limit-controls",
    ],
    description:
      "Fan and limit control for forced-air furnaces. Monitors plenum temperature and controls blower operation.",
    image: img("brushes"),
    inStock: true,
    rating: 4.7,
    reviewCount: 154,
    specs: {
      "Insertion Length": "11 in",
      Application: "Forced Air Furnace",
      Brand: "Johnson Controls",
    },
  },
  {
    handle: "novus-n1200-process-controller",
    title: "Universal Process Controller, PID, Dual Display",
    brand: "NOVUS",
    itemNumber: "6NV12",
    mfrModel: "N1200",
    price: 215.0,
    categorySlug: "temperature-controllers",
    categoryPath: [
      "hvac",
      "hvac-controls-and-thermostats",
      "temperature-controllers",
    ],
    description:
      "Panel-mount PID process controller for temperature and process loops. Dual display, multi-input.",
    image: img("tools_instruments"),
    inStock: true,
    rating: 4.8,
    reviewCount: 44,
    specs: {
      "Control Type": "PID",
      Inputs: "Thermocouple / RTD / Analog",
      Outputs: "Relay / SSR / Analog",
      "Panel Size": "1/16 DIN",
    },
  },
  {
    handle: "white-rodgers-furnace-control-board",
    title: "Integrated Furnace Control Board, 24V",
    brand: "WHITE-RODGERS",
    itemNumber: "4E960",
    mfrModel: "50A55-843",
    price: 198.4,
    categorySlug: "furnace-control-boards",
    categoryPath: [
      "hvac",
      "hvac-controls-and-thermostats",
      "hvac-equipment-controls",
      "furnace-control-boards",
    ],
    description:
      "Replacement integrated furnace control board for residential gas furnaces.",
    image: img("cutoff"),
    inStock: true,
    rating: 4.5,
    reviewCount: 89,
    specs: {
      Voltage: "24 VAC",
      Application: "Gas Furnace",
      Brand: "White-Rodgers",
    },
  },

  // —— Air Filters ——
  {
    handle: "aaf-flanders-pleated-filter-20x25x2",
    title: "Pleated Air Filter, 20 x 25 x 2 in, MERV 8",
    brand: "AAF FLANDERS",
    itemNumber: "3VE80",
    mfrModel: "PA20252",
    price: 12.45,
    categorySlug: "pleated-air-filters",
    categoryPath: [
      "hvac",
      "air-filters",
      "pleated-air-filters",
    ],
    description:
      "Standard capacity pleated HVAC filter for commercial and residential air handlers.",
    image: img("blasting"),
    inStock: true,
    rating: 4.6,
    reviewCount: 480,
    specs: {
      Size: "20 x 25 x 2 in",
      MERV: "8",
      "Filter Type": "Pleated",
      "Frame Material": "Beverage Board",
    },
  },
  {
    handle: "aaf-flanders-pleated-filter-16x25x4-merv13",
    title: "Pleated Air Filter, 16 x 25 x 4 in, MERV 13",
    brand: "AAF FLANDERS",
    itemNumber: "3VE95",
    mfrModel: "PA16254M13",
    price: 28.9,
    categorySlug: "pleated-air-filters",
    categoryPath: [
      "hvac",
      "air-filters",
      "pleated-air-filters",
    ],
    description: "High-efficiency MERV 13 pleated filter for improved IAQ.",
    image: img("blasting"),
    inStock: true,
    rating: 4.7,
    reviewCount: 201,
    specs: {
      Size: "16 x 25 x 4 in",
      MERV: "13",
      "Filter Type": "Pleated",
    },
  },
  {
    handle: "camfil-hepa-filter-24x24x12",
    title: "HEPA Filter, 24 x 24 x 12 in, 99.97%",
    brand: "CAMFIL",
    itemNumber: "5HEP1",
    mfrModel: "AbsoluteVG",
    price: 425.0,
    categorySlug: "hepa-filters",
    categoryPath: ["hvac", "air-filters", "hepa-filters"],
    description:
      "Absolute HEPA filter for cleanrooms and critical air handling applications.",
    image: img("blasting"),
    inStock: true,
    rating: 4.9,
    reviewCount: 23,
    specs: {
      Size: "24 x 24 x 12 in",
      Efficiency: "99.97% @ 0.3 µm",
      "Filter Type": "HEPA",
    },
  },

  // —— Cooling Fans / Ventilation ——
  {
    handle: "dayton-industrial-circulating-fan-30in",
    title: "Industrial Circulating Fan, 30 in, 115V, Pedestal",
    brand: "DAYTON",
    itemNumber: "4C548",
    mfrModel: "4C548",
    price: 319.0,
    categorySlug: "circulating-fans",
    categoryPath: [
      "hvac",
      "cooling-fans",
      "circulating-fans",
    ],
    description:
      "Heavy-duty pedestal circulating fan for warehouses and shops.",
    image: img("deburring"),
    inStock: true,
    rating: 4.5,
    reviewCount: 176,
    specs: {
      Diameter: "30 in",
      Voltage: "115V AC",
      CFM: "9200",
      Mount: "Pedestal",
    },
  },
  {
    handle: "dayton-exhaust-fan-wall-24in",
    title: "Wall Exhaust Fan, 24 in, Direct Drive, 115/230V",
    brand: "DAYTON",
    itemNumber: "1XJY8",
    mfrModel: "1XJY8",
    price: 485.75,
    categorySlug: "exhaust-fans",
    categoryPath: ["hvac", "cooling-fans", "exhaust-fans"],
    description: "Direct-drive wall exhaust fan for industrial ventilation.",
    image: img("deburring"),
    inStock: true,
    rating: 4.4,
    reviewCount: 61,
    specs: {
      Diameter: "24 in",
      Drive: "Direct",
      Voltage: "115/230V AC",
      CFM: "5400",
    },
  },

  // —— Air Conditioners ——
  {
    handle: "movincool-portable-spot-cooler-1ton",
    title: "Portable Spot Cooler, 12,000 BTU, 115V",
    brand: "MOVINCOOL",
    itemNumber: "6PCC1",
    mfrModel: "OfficePro12",
    price: 3899.0,
    categorySlug: "spot-coolers",
    categoryPath: [
      "hvac",
      "air-conditioners-evaporative-coolers",
      "spot-coolers",
    ],
    description:
      "Portable spot air conditioner for server rooms, events, and temporary cooling.",
    image: img("lighting_electrical"),
    inStock: true,
    rating: 4.7,
    reviewCount: 38,
    specs: {
      Capacity: "12,000 BTU",
      Voltage: "115V AC",
      Type: "Portable Spot Cooler",
    },
  },
  {
    handle: "lg-window-air-conditioner-10000btu",
    title: "Window Air Conditioner, 10,000 BTU, 115V",
    brand: "LG",
    itemNumber: "4WAC0",
    mfrModel: "LW1016ER",
    price: 429.0,
    categorySlug: "window-air-conditioners",
    categoryPath: [
      "hvac",
      "air-conditioners-evaporative-coolers",
      "window-air-conditioners",
    ],
    description: "Window-mounted room air conditioner with remote control.",
    image: img("lighting_electrical"),
    inStock: true,
    rating: 4.3,
    reviewCount: 520,
    specs: {
      Capacity: "10,000 BTU",
      Voltage: "115V AC",
      "Cooling Area": "450 sq ft",
    },
  },

  // —— Diagnostics ——
  {
    handle: "yellow-jacket-manifold-gauge-set",
    title: "Manifold Gauge Set, 2-Valve, R-134a / R-22 / R-404A",
    brand: "YELLOW JACKET",
    itemNumber: "3YR22",
    mfrModel: "42004",
    price: 168.2,
    categorySlug: "manifold-gauges",
    categoryPath: [
      "hvac",
      "hvac-diagnostics-recovery-evacuation",
      "manifold-gauges",
    ],
    description:
      "2-valve brass manifold gauge set for HVAC/R charging and diagnosis.",
    image: img("tools_instruments"),
    inStock: true,
    rating: 4.8,
    reviewCount: 267,
    specs: {
      Valves: "2",
      Refrigerants: "R-134a / R-22 / R-404A",
      "Hose Length": "60 in",
    },
  },
  {
    handle: "robinair-vacuum-pump-6cfm",
    title: "Vacuum Pump, 6 CFM, 2-Stage, 115V",
    brand: "ROBINAIR",
    itemNumber: "4VP06",
    mfrModel: "15600",
    price: 389.0,
    categorySlug: "vacuum-pumps",
    categoryPath: [
      "hvac",
      "hvac-diagnostics-recovery-evacuation",
      "vacuum-pumps",
    ],
    description: "Two-stage vacuum pump for HVAC system evacuation.",
    image: img("tools_instruments"),
    inStock: true,
    rating: 4.6,
    reviewCount: 112,
    specs: {
      CFM: "6",
      Stages: "2",
      Voltage: "115V AC",
    },
  },
  {
    handle: "inficon-refrigerant-leak-detector",
    title: "Refrigerant Leak Detector, Heated Diode",
    brand: "INFICON",
    itemNumber: "5LD88",
    mfrModel: "D-TEK Select",
    price: 549.0,
    categorySlug: "leak-detectors",
    categoryPath: [
      "hvac",
      "hvac-diagnostics-recovery-evacuation",
      "leak-detectors",
    ],
    description:
      "Heated diode refrigerant leak detector for field service technicians.",
    image: img("tools_instruments"),
    inStock: true,
    rating: 4.7,
    reviewCount: 91,
    specs: {
      Sensor: "Heated Diode",
      Sensitivity: "0.25 oz/yr",
      Refrigerants: "CFC / HCFC / HFC",
    },
  },

  // —— Refrigerants / Parts ——
  {
    handle: "forane-r410a-refrigerant-25lb",
    title: "R-410A Refrigerant, 25 lb Cylinder",
    brand: "FORANE",
    itemNumber: "4R410",
    mfrModel: "410A-25",
    price: 285.0,
    categorySlug: "refrigerants",
    categoryPath: [
      "hvac",
      "refrigerants-heat-transfer-fluids-lubricants",
      "refrigerants",
    ],
    description:
      "R-410A refrigerant cylinder for residential and light commercial AC systems. EPA certification required.",
    image: img("cutoff"),
    inStock: true,
    rating: 4.5,
    reviewCount: 33,
    specs: {
      Refrigerant: "R-410A",
      "Net Weight": "25 lb",
      "Requires Certification": "Yes",
    },
  },
  {
    handle: "mars-dual-run-capacitor-40-5",
    title: "Dual Run Capacitor, 40/5 MFD, 370V",
    brand: "MARS",
    itemNumber: "3CAP4",
    mfrModel: "12787",
    price: 18.75,
    categorySlug: "capacitors",
    categoryPath: [
      "hvac",
      "hvac-refrigeration-replacement-parts",
      "capacitors",
    ],
    description:
      "OEM-style dual run capacitor for compressor and fan motor circuits.",
    image: img("brushes"),
    inStock: true,
    rating: 4.6,
    reviewCount: 640,
    specs: {
      Capacitance: "40/5 MFD",
      Voltage: "370 VAC",
      Shape: "Round",
    },
  },
  {
    handle: "contactor-30a-2pole-24v",
    title: "Definite Purpose Contactor, 30A, 2-Pole, 24V Coil",
    brand: "SQUARE D",
    itemNumber: "2C301",
    mfrModel: "8911DPSA32V02",
    price: 42.1,
    categorySlug: "contactors-relays",
    categoryPath: [
      "hvac",
      "hvac-refrigeration-replacement-parts",
      "contactors-relays",
    ],
    description: "2-pole definite purpose contactor for HVAC compressors.",
    image: img("brushes"),
    inStock: true,
    rating: 4.7,
    reviewCount: 188,
    specs: {
      Amperage: "30 A",
      Poles: "2",
      "Coil Voltage": "24 VAC",
    },
  },

  // —— Sensors / probes (replacement parts) ——
  {
    handle: "johnson-controls-duct-temp-sensor",
    title: "Duct Temperature Sensor, 10k NTC, 8 in Probe",
    brand: "JOHNSON CONTROLS",
    itemNumber: "5SEN1",
    mfrModel: "TE-6001-1",
    price: 36.5,
    categorySlug: "sensors-probes",
    categoryPath: [
      "hvac",
      "hvac-refrigeration-replacement-parts",
      "sensors-probes",
    ],
    description:
      "Duct-mount temperature sensor for BAS and HVAC control systems.",
    image: img("tools_instruments"),
    inStock: true,
    rating: 4.5,
    reviewCount: 72,
    specs: {
      Sensor: "10k NTC",
      "Probe Length": "8 in",
      Mount: "Duct",
    },
  },
  {
    handle: "setra-differential-pressure-transmitter",
    title: "Differential Pressure Transmitter, 0-5 in. w.c., 4-20 mA",
    brand: "SETRA",
    itemNumber: "6DPT5",
    mfrModel: "Model 267",
    price: 312.0,
    categorySlug: "sensors-probes",
    categoryPath: [
      "hvac",
      "hvac-refrigeration-replacement-parts",
      "sensors-probes",
    ],
    description:
      "Low-pressure differential transmitter for filter monitoring and airflow applications.",
    image: img("tools_instruments"),
    inStock: true,
    rating: 4.8,
    reviewCount: 29,
    specs: {
      Range: "0-5 in. w.c.",
      Output: "4-20 mA",
      Accuracy: "±1% FS",
    },
  },

  // —— Cleaning ——
  {
    handle: "nu-calgon-coil-cleaner-gallon",
    title: "Evaporator Coil Cleaner, 1 Gallon, Foaming",
    brand: "NU-CALGON",
    itemNumber: "4CLN1",
    mfrModel: "4171-08",
    price: 24.99,
    categorySlug: "coil-cleaners",
    categoryPath: [
      "hvac",
      "hvac-cleaning-chemicals-equipment-kits",
      "coil-cleaners",
    ],
    description: "Foaming evaporator coil cleaner for HVAC maintenance.",
    image: img("sanding"),
    inStock: true,
    rating: 4.6,
    reviewCount: 155,
    specs: {
      Size: "1 Gallon",
      Type: "Foaming",
      Application: "Evaporator Coils",
    },
  },

  // —— Office heater ——
  {
    handle: "lantis-portable-office-heater-1500w",
    title: "Portable Electric Office Heater, 1500W, Ceramic, Oscillating",
    brand: "LASKO",
    itemNumber: "5OFF1",
    mfrModel: "754200",
    price: 49.99,
    categorySlug: "portable-electric-office-heaters",
    categoryPath: [
      "hvac",
      "heaters",
      "electric-heaters",
      "portable-electric-heaters",
      "portable-electric-office-heaters",
    ],
    description:
      "Compact ceramic office heater with adjustable thermostat and tip-over protection.",
    image: img("vibratory"),
    inStock: true,
    rating: 4.1,
    reviewCount: 890,
    specs: {
      Wattage: "1500 W",
      Voltage: "120V AC",
      Type: "Ceramic",
      Oscillating: "Yes",
    },
  },

  // —— Process heater ——
  {
    handle: "chromalox-immersion-heater-3kw",
    title: "Electric Immersion Process Heater, 3 kW, 240V, Screw Plug",
    brand: "CHROMALOX",
    itemNumber: "2PH30",
    mfrModel: "ARMT-3305",
    price: 412.0,
    categorySlug: "electric-process-heaters",
    categoryPath: [
      "hvac",
      "heaters",
      "electric-process-heaters",
    ],
    description:
      "Screw-plug immersion heater for tanks and process vessels.",
    image: img("cutoff"),
    inStock: true,
    rating: 4.6,
    reviewCount: 18,
    specs: {
      "Power Output": "3 kW",
      Voltage: "240V AC",
      Mount: "Screw Plug",
    },
  },

  // —— Gas heater ——
  {
    handle: "dayton-propane-salamander-150k",
    title: "Propane Salamander Heater, 150,000 BTU, Torpedo Style",
    brand: "DAYTON",
    itemNumber: "3LZ15",
    mfrModel: "3LZ15",
    price: 279.0,
    categorySlug: "gas-oil-kerosene-heaters",
    categoryPath: [
      "hvac",
      "heaters",
      "gas-oil-kerosene-heaters",
    ],
    description:
      "Portable propane-fired torpedo heater for outdoor and well-ventilated jobsite heating.",
    image: img("brushes"),
    inStock: true,
    rating: 4.4,
    reviewCount: 340,
    specs: {
      Fuel: "Propane",
      "BTU Output": "150,000",
      Style: "Torpedo / Salamander",
    },
  },
  // —— Scraped listings (Ago 2026) — Item # + price reales ——
  {
    handle: "johnson-controls-line-voltage-thermostat-42c006",
    title: "Line Voltage Thermostat",
    brand: "JOHNSON CONTROLS",
    itemNumber: "42C006",
    mfrModel: "N/A",
    price: 271.64,
    categorySlug: "nonprogrammable-line-voltage-thermostats",
    categoryPath: ["hvac","hvac-controls-and-thermostats","thermostats","room-thermostats","line-voltage-thermostats","nonprogrammable-line-voltage-thermostats"],
    description: "Line-voltage thermostat for electric heating applications.",
    image: img("tools_instruments"),
    inStock: true, rating: 4.5, reviewCount: 40,
    specs: { Type: "Line Voltage", Brand: "Johnson Controls" },
  },
  {
    handle: "dayton-line-volt-mechanical-tstat-6gvx8",
    title: "Line Volt Mechanical Tstat",
    brand: "DAYTON",
    itemNumber: "6GVX8",
    mfrModel: "N/A",
    price: 68.50,
    categorySlug: "nonprogrammable-line-voltage-thermostats",
    categoryPath: ["hvac","hvac-controls-and-thermostats","thermostats","room-thermostats","line-voltage-thermostats","nonprogrammable-line-voltage-thermostats"],
    description: "Mechanical line-voltage thermostat for baseboard and fan-forced heaters.",
    image: img("tools_instruments"),
    inStock: true, rating: 4.4, reviewCount: 88,
    specs: { Type: "Mechanical Line Voltage", Brand: "DAYTON" },
  },
  {
    handle: "robertshaw-line-volt-mechanical-tstat-361yg7",
    title: "Line Volt Mechanical Tstat",
    brand: "ROBERTSHAW",
    itemNumber: "361YG7",
    mfrModel: "N/A",
    price: 40.93,
    categorySlug: "nonprogrammable-line-voltage-thermostats",
    categoryPath: ["hvac","hvac-controls-and-thermostats","thermostats","room-thermostats","line-voltage-thermostats","nonprogrammable-line-voltage-thermostats"],
    description: "Robertshaw mechanical line-voltage thermostat.",
    image: img("tools_instruments"),
    inStock: true, rating: 4.3, reviewCount: 55,
    specs: { Brand: "ROBERTSHAW", Type: "Mechanical" },
  },
  {
    handle: "white-rodgers-thermostat-heat-only-413xf9",
    title: "Thermostat Heat Only",
    brand: "WHITE-RODGERS",
    itemNumber: "413XF9",
    mfrModel: "N/A",
    price: 53.66,
    categorySlug: "nonprogrammable-line-voltage-thermostats",
    categoryPath: ["hvac","hvac-controls-and-thermostats","thermostats","room-thermostats","line-voltage-thermostats","nonprogrammable-line-voltage-thermostats"],
    description: "Heat-only thermostat for electric heating systems.",
    image: img("tools_instruments"),
    inStock: true, rating: 4.5, reviewCount: 120,
    specs: { Brand: "WHITE-RODGERS", Application: "Heat Only" },
  },
  {
    handle: "honeywell-home-line-volt-tstat-4cz52",
    title: "Line Volt Mechanical Tstat",
    brand: "HONEYWELL HOME",
    itemNumber: "4CZ52",
    mfrModel: "N/A",
    price: 73.00,
    categorySlug: "nonprogrammable-line-voltage-thermostats",
    categoryPath: ["hvac","hvac-controls-and-thermostats","thermostats","room-thermostats","line-voltage-thermostats","nonprogrammable-line-voltage-thermostats"],
    description: "Honeywell Home mechanical line-voltage thermostat.",
    image: img("tools_instruments"),
    inStock: true, rating: 4.6, reviewCount: 200,
    specs: { Brand: "HONEYWELL HOME" },
  },
  {
    handle: "raychem-line-volt-electronic-tstat-45rk49",
    title: "Line Volt Electronic Tstat",
    brand: "RAYCHEM",
    itemNumber: "45RK49",
    mfrModel: "N/A",
    price: 610.04,
    categorySlug: "nonprogrammable-line-voltage-thermostats",
    categoryPath: ["hvac","hvac-controls-and-thermostats","thermostats","room-thermostats","line-voltage-thermostats","nonprogrammable-line-voltage-thermostats"],
    description: "Electronic line-voltage thermostat, often paired with heat-trace systems.",
    image: img("tools_instruments"),
    inStock: true, rating: 4.7, reviewCount: 15,
    specs: { Brand: "RAYCHEM", Type: "Electronic" },
  },
  {
    handle: "raychem-electric-heating-cable-2vev6",
    title: "Electric Heating Cable",
    brand: "RAYCHEM",
    itemNumber: "2VEV6",
    mfrModel: "N/A",
    price: 325.21,
    categorySlug: "cut-to-length-electric-heating-cables",
    categoryPath: ["hvac","heaters","electric-heaters","electric-heating-cables","cut-to-length-electric-heating-cables"],
    description: "Cut-to-length self-regulating electric heating cable.",
    image: img("buffing"),
    inStock: true, rating: 4.6, reviewCount: 30,
    specs: { Brand: "RAYCHEM", Type: "Self-Regulating" },
  },
  {
    handle: "raychem-electric-heating-cable-2vev8",
    title: "Electric Heating Cable",
    brand: "RAYCHEM",
    itemNumber: "2VEV8",
    mfrModel: "N/A",
    price: 394.93,
    categorySlug: "cut-to-length-electric-heating-cables",
    categoryPath: ["hvac","heaters","electric-heaters","electric-heating-cables","cut-to-length-electric-heating-cables"],
    description: "Cut-to-length self-regulating electric heating cable.",
    image: img("buffing"),
    inStock: true, rating: 4.6, reviewCount: 22,
    specs: { Brand: "RAYCHEM" },
  },
  {
    handle: "dayton-wall-ceiling-heater-10kw-804rz6",
    title: "Wall Ceiling Heater 10 kW",
    brand: "DAYTON",
    itemNumber: "804RZ6",
    mfrModel: "N/A",
    price: 1297.14,
    categorySlug: "electric-wall-ceiling-heaters",
    categoryPath: ["hvac","heaters","electric-heaters","electric-wall-ceiling-heaters"],
    description: "Suspended electric wall & ceiling unit heater, 10 kW.",
    image: img("lighting_electrical"),
    inStock: true, rating: 4.5, reviewCount: 12,
    specs: { "Power Output": "10 kW", Brand: "DAYTON", Mount: "Wall/Ceiling" },
  },
  {
    handle: "dayton-wall-ceiling-heater-15kw-804rz9",
    title: "Wall Ceiling Heater 15 kW",
    brand: "DAYTON",
    itemNumber: "804RZ9",
    mfrModel: "N/A",
    price: 2567.86,
    categorySlug: "electric-wall-ceiling-heaters",
    categoryPath: ["hvac","heaters","electric-heaters","electric-wall-ceiling-heaters"],
    description: "Suspended electric wall & ceiling unit heater, 15 kW.",
    image: img("lighting_electrical"),
    inStock: true, rating: 4.5, reviewCount: 8,
    specs: { "Power Output": "15 kW", Brand: "DAYTON" },
  },
  {
    handle: "cn-pleated-air-filter-4e505",
    title: "Pleated Air Filter 12 in",
    brand: "CONTROL NAUTAS",
    itemNumber: "4E505",
    mfrModel: "N/A",
    price: 5.72,
    categorySlug: "merv-8-pleated-air-filters",
    categoryPath: ["hvac","air-filters","panel-and-pleated-air-filters","pleated-air-filters","merv-8-pleated-air-filters"],
    description: "Pleated HVAC air filter, 12 in.",
    image: img("blasting"),
    inStock: true, rating: 4.4, reviewCount: 300,
    specs: { Brand: "CONTROL NAUTAS", "Filter Type": "Pleated" },
  },
  {
    handle: "cn-pleated-air-filter-6b951",
    title: "Pleated Air Filter 16 in",
    brand: "CONTROL NAUTAS",
    itemNumber: "6B951",
    mfrModel: "N/A",
    price: 8.24,
    categorySlug: "merv-8-pleated-air-filters",
    categoryPath: ["hvac","air-filters","panel-and-pleated-air-filters","pleated-air-filters","merv-8-pleated-air-filters"],
    description: "Pleated HVAC air filter, 16 in.",
    image: img("blasting"),
    inStock: true, rating: 4.4, reviewCount: 250,
    specs: { Brand: "CONTROL NAUTAS" },
  },
  {
    handle: "master-circulating-fan-12in-401vj3",
    title: "Circulating Fan 12 in Blade",
    brand: "MASTER",
    itemNumber: "401VJ3",
    mfrModel: "N/A",
    price: 143.08,
    categorySlug: "standard-industrial-floor-fans",
    categoryPath: ["hvac","cooling-fans","industrial-cooling-fans","industrial-floor-fans","standard-industrial-floor-fans"],
    description: "12 in circulating fan for industrial and shop cooling.",
    image: img("deburring"),
    inStock: true, rating: 4.3, reviewCount: 45,
    specs: { Diameter: "12 in", Brand: "MASTER" },
  },
  {
    handle: "patterson-cooling-fan-18in-818gk9",
    title: "Cooling Fan 18 in Blade Dia",
    brand: "PATTERSON",
    itemNumber: "818GK9",
    mfrModel: "N/A",
    price: 252.30,
    categorySlug: "standard-industrial-floor-fans",
    categoryPath: ["hvac","cooling-fans","industrial-cooling-fans","industrial-floor-fans","standard-industrial-floor-fans"],
    description: "18 in industrial cooling fan.",
    image: img("deburring"),
    inStock: true, rating: 4.5, reviewCount: 33,
    specs: { Diameter: "18 in", Brand: "PATTERSON" },
  },
  {
    handle: "tpi-industrial-circulating-fan-373j18",
    title: "Circulating Fan",
    brand: "TPI INDUSTRIAL",
    itemNumber: "373J18",
    mfrModel: "N/A",
    price: 259.84,
    categorySlug: "standard-industrial-floor-fans",
    categoryPath: ["hvac","cooling-fans","industrial-cooling-fans","industrial-floor-fans","standard-industrial-floor-fans"],
    description: "TPI Industrial circulating fan.",
    image: img("deburring"),
    inStock: true, rating: 4.4, reviewCount: 27,
    specs: { Brand: "TPI INDUSTRIAL" },
  },
]

export function getProductByHandle(handle: string): HvacProduct | undefined {
  return HVAC_PRODUCTS.find((p) => p.handle === handle)
}

export function getProductsByCategorySlug(slug: string): HvacProduct[] {
  return HVAC_PRODUCTS.filter(
    (p) => p.categorySlug === slug || p.categoryPath.includes(slug)
  )
}

export function getAllBrands(): string[] {
  return Array.from(new Set(HVAC_PRODUCTS.map((p) => p.brand))).sort()
}

export function formatPrice(amount: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(amount)
}
